/**
 * Cross-chain settlement integration for StellarSplit SDK.
 *
 * Provides a pluggable adapter architecture for initiating, tracking, and
 * managing cross-chain settlement of invoice payments. Adapters encapsulate
 * the chain-specific logic (fee estimation, transaction submission, and status
 * polling) while the service layer provides a unified API and event bus.
 *
 * @example
 * ```ts
 * const service = new CrossChainSettlementService();
 * service.registerChain("ethereum", myEthAdapter);
 *
 * const { settlementId } = await service.initiateSettlement({
 *   sourceChain: "stellar",
 *   targetChain: "ethereum",
 *   amount: 100_000_000n,
 *   recipient: "0xdeadbeef...",
 *   token: "USDC",
 * });
 * ```
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A stable identifier for a registered chain adapter. */
export type ChainId = string;

/**
 * Parameters required to estimate fees or submit a cross-chain transfer.
 */
export interface ChainTransferParams {
  /** Source chain identifier (e.g. `"stellar"`, `"ethereum"`). */
  sourceChain: ChainId;
  /** Destination chain identifier (e.g. `"polygon"`, `"solana"`). */
  targetChain: ChainId;
  /** Transfer amount in the smallest token unit (e.g. stroops for XLM). */
  amount: bigint;
  /** Recipient address on the target chain. */
  recipient: string;
  /** Token identifier or contract address (e.g. `"USDC"`, `"0xA0b8..."`) */
  token: string;
}

/** Parameters accepted by {@link CrossChainSettlementService.initiateSettlement}. */
export type SettlementParams = ChainTransferParams;

/** Possible lifecycle states of a settlement. */
export type SettlementStatus =
  | "pending"
  | "submitted"
  | "confirmed"
  | "failed"
  | "unknown";

/** A snapshot of a single cross-chain settlement operation. */
export interface Settlement {
  /** Unique identifier generated by the service. */
  readonly id: string;
  /** The original parameters this settlement was created from. */
  readonly params: Readonly<SettlementParams>;
  /** Current lifecycle status. */
  status: SettlementStatus;
  /** Chain-native transaction ID returned by the adapter after submission. */
  txId?: string;
  /** ISO 8601 timestamp when the settlement was created. */
  readonly createdAt: string;
  /** ISO 8601 timestamp of the last status update. */
  updatedAt: string;
  /** Human-readable error message when `status === "failed"`. */
  error?: string;
}

/**
 * Estimated fee breakdown returned by {@link ChainAdapter.estimateFee}.
 */
export interface FeeEstimate {
  /** Native fee amount in the source chain's smallest unit. */
  fee: bigint;
  /** Human-readable token symbol for the fee (e.g. `"ETH"`, `"XLM"`). */
  feeToken: string;
  /** Estimated fee as a decimal string for display (e.g. `"0.001"`). */
  feeDisplay: string;
}

/**
 * Result returned by {@link ChainAdapter.submit}.
 */
export interface SubmitResult {
  /** Chain-native transaction identifier. */
  txId: string;
  /** Initial status at submission time. */
  status: SettlementStatus;
}

/**
 * Result returned by {@link ChainAdapter.getStatus}.
 */
export interface StatusResult {
  /** Current status of the on-chain transaction. */
  status: SettlementStatus;
  /** Optional human-readable error detail when `status === "failed"`. */
  error?: string;
}

// ---------------------------------------------------------------------------
// ChainAdapter interface
// ---------------------------------------------------------------------------

/**
 * Pluggable adapter that encapsulates chain-specific logic.
 *
 * Implement this interface and pass instances to
 * {@link CrossChainSettlementService.registerChain} to support additional
 * chains without modifying SDK internals.
 *
 * @example
 * ```ts
 * class MyEthAdapter implements ChainAdapter {
 *   async estimateFee(params) { ... }
 *   async submit(params) { ... }
 *   async getStatus(txId) { ... }
 * }
 * ```
 */
export interface ChainAdapter {
  /**
   * Estimate the fee required to execute the given transfer.
   *
   * This method MUST NOT submit any transaction or consume a sequence number.
   *
   * @param params - Transfer parameters to estimate fees for.
   * @returns A {@link FeeEstimate} describing the expected cost.
   */
  estimateFee(params: ChainTransferParams): Promise<FeeEstimate>;

  /**
   * Submit the cross-chain transfer and return the native transaction ID.
   *
   * @param params - Transfer parameters to submit.
   * @returns A {@link SubmitResult} with the transaction ID and initial status.
   */
  submit(params: ChainTransferParams): Promise<SubmitResult>;

  /**
   * Query the on-chain status of a previously submitted transaction.
   *
   * @param txId - The transaction identifier returned by {@link submit}.
   * @returns A {@link StatusResult} reflecting the current on-chain state.
   */
  getStatus(txId: string): Promise<StatusResult>;
}

// ---------------------------------------------------------------------------
// Event map
// ---------------------------------------------------------------------------

/**
 * Events emitted by {@link CrossChainSettlementService}.
 *
 * Subscribe via the service's `on()` / `off()` API:
 *
 * ```ts
 * service.on("settlement:initiated", (settlement) => { ... });
 * ```
 */
export interface CrossChainSettlementEvents {
  /**
   * Fired immediately after a settlement record is created and the adapter's
   * `submit()` call has been dispatched.
   */
  "settlement:initiated": Settlement;
  /**
   * Fired when the adapter's `getStatus()` or the initial `submit()` result
   * indicates the transaction has been confirmed on-chain.
   */
  "settlement:confirmed": Settlement;
  /**
   * Fired when the adapter signals a permanent failure (non-retryable) or an
   * unexpected error prevents the settlement from completing.
   */
  "settlement:failed": Settlement & { error: string };
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/** Thrown when attempting to use a chain ID that has no registered adapter. */
export class UnregisteredChainError extends Error {
  constructor(chainId: ChainId) {
    super(`No adapter registered for chain "${chainId}"`);
    this.name = "UnregisteredChainError";
  }
}

/** Thrown when a settlement ID is not found in the in-memory store. */
export class SettlementNotFoundError extends Error {
  constructor(id: string) {
    super(`Settlement "${id}" not found`);
    this.name = "SettlementNotFoundError";
  }
}

/** Thrown when settlement parameters fail basic validation. */
export class SettlementValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SettlementValidationError";
  }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Simple monotonic counter used to generate deterministic settlement IDs. */
let _counter = 0;

function generateSettlementId(): string {
  const ts = Date.now().toString(36);
  const seq = (++_counter).toString(36).padStart(4, "0");
  return `settle-${ts}-${seq}`;
}

function nowIso(): string {
  return new Date().toISOString();
}

type EventListener<T> = (payload: T) => void;

// ---------------------------------------------------------------------------
// CrossChainSettlementService
// ---------------------------------------------------------------------------

/**
 * Manages the full lifecycle of cross-chain settlement operations.
 *
 * Responsibilities:
 *  - Maintaining a registry of {@link ChainAdapter} instances keyed by chain ID.
 *  - Creating, storing, and updating {@link Settlement} records.
 *  - Emitting typed lifecycle events (`settlement:initiated`,
 *    `settlement:confirmed`, `settlement:failed`).
 *
 * The service does **not** depend on any external libraries — it is a pure
 * TypeScript class suitable for use in Node, browser, and edge runtimes.
 *
 * @example
 * ```ts
 * const service = new CrossChainSettlementService();
 * service.registerChain("ethereum", ethAdapter);
 *
 * service.on("settlement:confirmed", (s) =>
 *   console.log("Confirmed:", s.id, s.txId),
 * );
 *
 * const { settlementId } = await service.initiateSettlement({
 *   sourceChain: "stellar",
 *   targetChain: "ethereum",
 *   amount: 50_000_000n,
 *   recipient: "0xABCDEF...",
 *   token: "USDC",
 * });
 * ```
 */
export class CrossChainSettlementService {
  /** Chain adapter registry: chainId → adapter. */
  private readonly adapters = new Map<ChainId, ChainAdapter>();

  /** In-memory settlement store: settlementId → Settlement. */
  private readonly settlements = new Map<string, Settlement>();

  /** Typed event listener registry. */
  private readonly listeners: {
    [K in keyof CrossChainSettlementEvents]?: Set<
      EventListener<CrossChainSettlementEvents[K]>
    >;
  } = {};

  // -------------------------------------------------------------------------
  // Adapter registry
  // -------------------------------------------------------------------------

  /**
   * Register a {@link ChainAdapter} for the given chain ID.
   *
   * Overwrites any previously registered adapter for the same chain ID.
   *
   * @param chainId - A unique identifier for the chain (e.g. `"ethereum"`).
   * @param adapter - The adapter instance to register.
   */
  registerChain(chainId: ChainId, adapter: ChainAdapter): void {
    if (!chainId || typeof chainId !== "string") {
      throw new SettlementValidationError("chainId must be a non-empty string");
    }
    this.adapters.set(chainId, adapter);
  }

  /**
   * Retrieve the registered adapter for a chain ID, or `undefined` if none.
   *
   * @param chainId - The chain ID to look up.
   */
  getAdapter(chainId: ChainId): ChainAdapter | undefined {
    return this.adapters.get(chainId);
  }

  /**
   * Returns the set of chain IDs that currently have a registered adapter.
   */
  registeredChains(): ChainId[] {
    return Array.from(this.adapters.keys());
  }

  // -------------------------------------------------------------------------
  // Settlement operations
  // -------------------------------------------------------------------------

  /**
   * Initiate a cross-chain settlement.
   *
   * Validates the parameters, creates a {@link Settlement} record, delegates
   * to the target chain's adapter, and emits `settlement:initiated`. If the
   * adapter immediately reports a confirmed status, `settlement:confirmed` is
   * also emitted before this method returns.
   *
   * @param params - Transfer parameters.
   * @returns An object with the `settlementId` and the full initial
   *   {@link Settlement} record.
   * @throws {SettlementValidationError} If parameters fail validation.
   * @throws {UnregisteredChainError} If no adapter is registered for
   *   `params.targetChain`.
   */
  async initiateSettlement(
    params: SettlementParams,
  ): Promise<{ settlementId: string; settlement: Settlement }> {
    this.validateParams(params);

    const adapter = this.adapters.get(params.targetChain);
    if (!adapter) {
      throw new UnregisteredChainError(params.targetChain);
    }

    const id = generateSettlementId();
    const now = nowIso();

    const settlement: Settlement = {
      id,
      params: Object.freeze({ ...params }),
      status: "pending",
      createdAt: now,
      updatedAt: now,
    };

    this.settlements.set(id, settlement);

    // Emit initiated event before the async submit so listeners can observe
    // the pending state.
    this.emit("settlement:initiated", { ...settlement });

    try {
      const result = await adapter.submit(params);

      settlement.txId = result.txId;
      settlement.status = result.status === "confirmed" ? "confirmed" : "submitted";
      settlement.updatedAt = nowIso();

      if (settlement.status === "confirmed") {
        this.emit("settlement:confirmed", { ...settlement });
      }
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      settlement.status = "failed";
      settlement.error = message;
      settlement.updatedAt = nowIso();
      this.emit("settlement:failed", {
        ...(settlement as Settlement & { error: string }),
      });
    }

    return { settlementId: id, settlement };
  }

  /**
   * Fetch the current status of a settlement by refreshing it from the
   * adapter.
   *
   * If the settlement already has a terminal status (`confirmed` or `failed`),
   * the stored record is returned immediately without querying the adapter.
   *
   * @param id - The settlement ID returned by {@link initiateSettlement}.
   * @returns The (possibly updated) {@link Settlement} record.
   * @throws {SettlementNotFoundError} If no settlement with the given ID
   *   exists.
   * @throws {UnregisteredChainError} If the adapter for the settlement's
   *   target chain has been evicted since initiation.
   */
  async getSettlementStatus(id: string): Promise<Settlement> {
    const settlement = this.settlements.get(id);
    if (!settlement) {
      throw new SettlementNotFoundError(id);
    }

    // Terminal states do not need re-querying.
    if (settlement.status === "confirmed" || settlement.status === "failed") {
      return { ...settlement };
    }

    // We need a txId to query the adapter.
    if (!settlement.txId) {
      return { ...settlement };
    }

    const adapter = this.adapters.get(settlement.params.targetChain);
    if (!adapter) {
      throw new UnregisteredChainError(settlement.params.targetChain);
    }

    try {
      const statusResult = await adapter.getStatus(settlement.txId);
      const previousStatus = settlement.status;

      settlement.status = statusResult.status;
      if (statusResult.error) {
        settlement.error = statusResult.error;
      }
      settlement.updatedAt = nowIso();

      // Emit transition events.
      if (previousStatus !== "confirmed" && settlement.status === "confirmed") {
        this.emit("settlement:confirmed", { ...settlement });
      } else if (previousStatus !== "failed" && settlement.status === "failed") {
        settlement.error ??= "Unknown failure";
        this.emit("settlement:failed", {
          ...(settlement as Settlement & { error: string }),
        });
      }
    } catch (err: unknown) {
      // Treat adapter errors as unknown — do not transition to failed, since
      // the transaction might still be in-flight.
      settlement.status = "unknown";
      settlement.updatedAt = nowIso();
    }

    return { ...settlement };
  }

  /**
   * Return a snapshot of all settlements currently held in memory, ordered by
   * creation time (oldest first).
   *
   * @returns An array of {@link Settlement} records (copies, not references).
   */
  listSettlements(): Settlement[] {
    return Array.from(this.settlements.values())
      .sort((a, b) => a.createdAt.localeCompare(b.createdAt))
      .map((s) => ({ ...s }));
  }

  /**
   * Estimate the fee for a prospective settlement without submitting it.
   *
   * Delegates directly to the target chain adapter's `estimateFee` method.
   *
   * @param params - Transfer parameters to estimate fees for.
   * @returns A {@link FeeEstimate} from the adapter.
   * @throws {SettlementValidationError} If parameters fail validation.
   * @throws {UnregisteredChainError} If no adapter is registered for
   *   `params.targetChain`.
   */
  async estimateFee(params: SettlementParams): Promise<FeeEstimate> {
    this.validateParams(params);

    const adapter = this.adapters.get(params.targetChain);
    if (!adapter) {
      throw new UnregisteredChainError(params.targetChain);
    }

    return adapter.estimateFee(params);
  }

  // -------------------------------------------------------------------------
  // Event API
  // -------------------------------------------------------------------------

  /**
   * Register an event listener.
   *
   * @param event - One of the settlement lifecycle event names.
   * @param listener - Callback invoked with the event payload.
   * @returns An unsubscribe function that removes the listener.
   */
  on<K extends keyof CrossChainSettlementEvents>(
    event: K,
    listener: EventListener<CrossChainSettlementEvents[K]>,
  ): () => void {
    let set = this.listeners[event];
    if (!set) {
      set = new Set();
      this.listeners[event] = set as Set<EventListener<CrossChainSettlementEvents[K]>>;
    }
    (set as Set<EventListener<CrossChainSettlementEvents[K]>>).add(listener);
    return () => this.off(event, listener);
  }

  /**
   * Remove a previously registered event listener.
   *
   * @param event - Event name.
   * @param listener - The listener to remove.
   */
  off<K extends keyof CrossChainSettlementEvents>(
    event: K,
    listener: EventListener<CrossChainSettlementEvents[K]>,
  ): void {
    (this.listeners[event] as Set<EventListener<CrossChainSettlementEvents[K]>> | undefined)?.delete(
      listener,
    );
  }

  /**
   * Remove all listeners for a specific event, or every listener if called
   * without arguments.
   *
   * @param event - Optional event name. Omit to clear all events.
   */
  removeAllListeners(event?: keyof CrossChainSettlementEvents): void {
    if (event === undefined) {
      for (const key of Object.keys(this.listeners) as Array<keyof CrossChainSettlementEvents>) {
        delete this.listeners[key];
      }
    } else {
      delete this.listeners[event];
    }
  }

  /**
   * Returns the number of listeners currently registered for `event`.
   *
   * @param event - Event name.
   */
  listenerCount(event: keyof CrossChainSettlementEvents): number {
    return this.listeners[event]?.size ?? 0;
  }

  // -------------------------------------------------------------------------
  // Private helpers
  // -------------------------------------------------------------------------

  private emit<K extends keyof CrossChainSettlementEvents>(
    event: K,
    payload: CrossChainSettlementEvents[K],
  ): void {
    const set = this.listeners[event] as
      | Set<EventListener<CrossChainSettlementEvents[K]>>
      | undefined;
    if (set) {
      for (const listener of Array.from(set)) {
        try {
          listener(payload);
        } catch {
          // Listener errors must not crash the service.
        }
      }
    }
  }

  private validateParams(params: SettlementParams): void {
    if (!params.sourceChain || typeof params.sourceChain !== "string") {
      throw new SettlementValidationError("sourceChain must be a non-empty string");
    }
    if (!params.targetChain || typeof params.targetChain !== "string") {
      throw new SettlementValidationError("targetChain must be a non-empty string");
    }
    if (params.sourceChain === params.targetChain) {
      throw new SettlementValidationError(
        "sourceChain and targetChain must be different",
      );
    }
    if (typeof params.amount !== "bigint" || params.amount <= 0n) {
      throw new SettlementValidationError("amount must be a positive bigint");
    }
    if (!params.recipient || typeof params.recipient !== "string") {
      throw new SettlementValidationError("recipient must be a non-empty string");
    }
    if (!params.token || typeof params.token !== "string") {
      throw new SettlementValidationError("token must be a non-empty string");
    }
  }
}
